# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  SprintF\Bundle\Wolfflow\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'

  SprintF\Bundle\Wolfflow\Action\ActionAbstract:
    properties:
      workflows: SprintF\Bundle\Wolfflow\Workflow\WorkflowCollection
      actorProvider: SprintF\Bundle\Wolfflow\Actor\ActorProvider

parameters:
